Repository Tougrel/Pestoverse, pull requests merged in 2023-12, with the labels that each got.

#71 feat(auth): Add discord authentication to the website
  .yarn/cache/@auth-core-npm-0.18.4-edfa119e28-5ff5c17091.zip
  .yarn/cache/@headlessui-tailwindcss-npm-0.2.0-2ada2bf12b-a757991027.zip
  .yarn/cache/@hebilicious-authjs-nuxt-npm-0.3.5-7624fd9043-fd82a8f927.zip
  .yarn/cache/@nuxt-ui-npm-2.11.0-2fc9a0bc03-bc2a8ae4b3.zip
  .yarn/cache/@nuxthq-ui-npm-2.7.0-6519d703ac-7e266d6810.zip
  .yarn/cache/@panva-hkdf-npm-1.1.1-f16d36bb8a-f0dd129037.zip
  .yarn/cache/cookie-npm-0.5.0-e2d58a161a-1f4bd2ca57.zip
  .yarn/cache/cookie-npm-0.6.0-362d6a2e45-f56a7d32a0.zip
  .yarn/cache/immer-npm-10.0.3-174ab52899-76acabe6f4.zip
  .yarn/cache/jose-npm-4.15.4-c518ec3da8-dccad91cb3.zip
  .yarn/cache/jose-npm-5.1.3-10a30371cc-c0225c3408.zip
  .yarn/cache/lodash-es-npm-4.17.21-b45832dfce-05cbffad6e.zip
  .yarn/cache/oauth4webapi-npm-2.4.0-8caded8d06-9e6d5be396.zip
  .yarn/cache/preact-npm-10.11.3-4973d2dda6-9387115aa0.zip
  .yarn/cache/preact-render-to-string-npm-5.2.3-1f72a2f38e-6e46288d89.zip
  .yarn/cache/pretty-format-npm-3.8.0-293db331d9-21a114d43e.zip
  .yarn/cache/tailwind-merge-npm-1.14.0-f448a138df-8cf5d37f51.zip
  app.config.ts
  app.vue
  components/map/popup.vue
  components/map/view.vue
  components/ui/Authentication.vue
  components/ui/ColorPicker.vue
  components/ui/NavMenu.vue
  nuxt.config.ts
  package.json
  pages/awards.vue
  server/api/auth/[...].ts
  types/auth.d.ts
  types/index.ts
  utils/index.ts
  yarn.lock
Labels: enhancement, dependencies

#75 feat: add toast on submission
  app.vue
  pages/awards.vue
Labels: enhancement

#78 fix: trim values to prevent duplicates
  server/api/submissions/submit.post.ts
Labels: bug

#81 Feat/reduce suggestions cache
  server/api/submissions/names.get.ts
  server/db/cache.ts
Labels: enhancement

#83 feat: lowercase submissions and suggestions
  server/api/submissions/names.get.ts
  server/api/submissions/submit.post.ts
Labels: enhancement

#85 feat: migrate from userId -> discordId and simplify submission logic …
  server/api/submissions/index.get.ts
  server/api/submissions/submit.post.ts
  server/db/migrations/0001_smiling_mother_askani.sql
  server/db/migrations/meta/0001_snapshot.json
  server/db/migrations/meta/_journal.json
  server/db/schema.ts
  server/db/submissions.ts
Labels: bug, enhancement

#86 Sort Suggestions
  .env.example
  server/api/submissions/names.get.ts
Labels: bug
