Repository Tougrel/Pestoverse, pull requests merged in 2023-07, with the labels that each got.

#5 feat: Loading animaton and server version route
  app.vue
  components/ui/loading.vue
  server/api/version.get.ts
  static/images/emotes/pestoNoted.webp
  static/images/emotes/waddle.gif
  utils/credits.ts
Labels: enhancement

#2 bundle images into output
  .yarn/install-state.gz
  components/credits/user.vue
  error.vue
  nuxt.config.ts
  pages/credits.vue
  utils/credits.ts
Labels: bug

#13 Add kudo boards in the menu as a slideover
  app.config.ts
  app.vue
  assets/css/index.css
  components/kudo/card.vue
  components/kudo/sidebar.vue
  components/ui/loading.vue
  static/images/emotes/dance.gif
  utils/index.ts
Labels: enhancement

#16 docs(readme): added crowdin and cloudflare badges and instructions on how to test locally
  README.md
Labels: documentation

#18 feat: add gallery
  app.config.ts
  components/credits/user.vue
  components/map/view.vue
  components/ui/slideover.vue
  content/gallery/ercburger.md
  content/gallery/no-coordinates.md
  pages/gallery.vue
  pages/index.vue
  static/images/credits/bootfighter.webp
  static/images/credits/dhoru.webp
  static/images/credits/ikanexus.webp
  static/images/credits/tougrel.webp
  static/images/credits/yuniiho.webp
  static/images/emotes/pestoBinoculars.webp
  utils/credits.ts
  utils/index.ts
Labels: enhancement

#24 feat: added favicon related stuff
  .yarn/install-state.gz
  app.vue
  public/browserconfig.xml
  public/favicon.ico
  public/icons/android-chrome-96x96.png
  public/icons/apple-touch-icon.png
  public/icons/favicon-16x16.png
  public/icons/favicon-32x32.png
  public/icons/mstile-150x150.png
  public/icons/safari-pinned-tab.svg
  public/site.webmanifest
Labels: enhancement

#25 feat: new theme selector and colors
  .gitignore
  app.vue
  components/credits/user.vue
  components/kudo/card.vue
  components/ui/colorPicker.vue
  components/ui/nav.vue
  nuxt.config.ts
  pages/credits.vue
  pages/gallery.vue
  pages/index.vue
  utils/index.ts
Labels: enhancement

#26 feat: add yoclesh to credits for emote
  .yarn/install-state.gz
  static/images/credits/yoclesh.webp
  utils/credits.ts
Labels: enhancement

#28 fix: slideover modal bug
  components/map/view.vue
  components/ui/slideover.vue
Labels: bug

#29 feat: add confetti on homepage
  .yarn/cache/@types-canvas-confetti-npm-1.6.0-f81e670b3e-e1bd2bc81e.zip
  .yarn/cache/canvas-confetti-npm-1.6.0-6705a317f0-be19e3be73.zip
  .yarn/install-state.gz
  components/easter-egg/confetti.vue
  package.json
  pages/index.vue
  yarn.lock
Labels: enhancement

#30 fix: prettier outdated plugin
  .prettierignore
  .prettierrc
  .yarn/cache/prettier-plugin-tailwindcss-npm-0.3.0-a8491b7f62-007c095584.zip
  .yarn/cache/prettier-plugin-tailwindcss-npm-0.4.1-280e71424b-9bdf3b7c27.zip
  .yarn/install-state.gz
  .yarnrc.yml
  package.json
  yarn.lock
Labels: bug, dependencies

#31 feat/fonts
  .yarn/cache/@nuxt-kit-npm-3.6.3-f877066d6a-08538308be.zip
  .yarn/cache/@nuxt-schema-npm-3.6.3-af1d23454b-0f18fa8800.zip
  .yarn/cache/@nuxtjs-google-fonts-npm-3.0.1-6af0dd04c2-8ac90e9f86.zip
  .yarn/cache/google-fonts-helper-npm-3.3.0-0f6f513a28-5710dc77b9.zip
  .yarn/install-state.gz
  app.config.ts
  app.vue
  components/credits/user.vue
  components/easter-egg/button.vue
  components/easter-egg/confetti.vue
  components/easter-egg/orbit.vue
  components/kudo/card.vue
  components/kudo/sidebar.vue
  components/map/view.vue
  components/ui/colorPicker.vue
  components/ui/loading.vue
  components/ui/nav.vue
  components/ui/slideover.vue
  error.vue
  layouts/default.vue
  nuxt.config.ts
  package.json
  pages/credits.vue
  pages/gallery.vue
  pages/index.vue
  pages/map.vue
  server/api/version.get.ts
  tailwind.config.ts
  types/marker.ts
  utils/credits.ts
  utils/emotes.ts
  utils/index.ts
  yarn.lock
Labels: enhancement, dependencies

#32 feat: new layout changes
  app.vue
  components/easter-egg/button.vue
  components/kudo/sidebar.vue
  components/ui/ColorPicker.vue
  components/ui/Footer.vue
  components/ui/LoadingScreen.vue
  components/ui/NavMenu.vue
  components/ui/SlideOver.vue
  components/ui/nav.vue
  layouts/default.vue
  layouts/map.vue
  pages/credits.vue
  pages/gallery.vue
  pages/index.vue
  pages/map.vue
  static/images/credits/vihilsta.webp
  utils/credits.ts
  utils/index.ts
Labels: enhancement

#33 Feat/fire for effect
  components/easter-egg/confetti.vue
Labels: enhancement

#34 feat: switch map to use tileserver-gl and openlayers
  .yarn/cache/@mapbox-jsonlint-lines-primitives-npm-2.0.2-f48e04c479-4eb31edd3c.zip
  .yarn/cache/@mapbox-mapbox-gl-style-spec-npm-13.28.0-3183e1b135-17246a849c.zip
  .yarn/cache/@mapbox-point-geometry-npm-0.1.0-d0fd1852be-ed41c1ce01.zip
  .yarn/cache/@mapbox-unitbezier-npm-0.0.0-159cc70ee6-22ae6d56f7.zip
  .yarn/cache/@petamoriken-float16-npm-3.8.1-d6208f174b-06d030e036.zip
  .yarn/cache/@types-geojson-npm-7946.0.10-deca8d1263-12c407c2dc.zip
  .yarn/cache/@types-leaflet-npm-1.9.3-7730c8a88b-d12042edc3.zip
  .yarn/cache/csscolorparser-npm-1.0.3-cd8e162bc9-e40f3045ea.zip
  .yarn/cache/earcut-npm-2.2.4-e823546b2f-aea0466cb2.zip
  .yarn/cache/geotiff-npm-2.0.7-de2232eb39-d64bd3c3cf.zip
  .yarn/cache/json-stringify-pretty-compact-npm-2.0.0-6fbd5abdc9-b476aa4ce2.zip
  .yarn/cache/leaflet-npm-1.9.4-8d372b0fe6-bfc79f17a2.zip
  .yarn/cache/lerc-npm-3.0.0-1c5ddc5593-637699a135.zip
  .yarn/cache/mapbox-to-css-font-npm-2.4.2-c12e8c4b1d-d7fd9339cf.zip
  .yarn/cache/ol-mapbox-style-npm-10.6.0-b74e20f903-41ed5cc4c3.zip
  .yarn/cache/ol-npm-7.4.0-dc001833fa-0cc8cfbbb0.zip
  .yarn/cache/pako-npm-2.1.0-78df11948c-7166654864.zip
  .yarn/cache/parse-headers-npm-2.0.5-c1f2d79179-3e97f01e4c.zip
  .yarn/cache/pbf-npm-3.2.1-d33be8e429-8033f5e21f.zip
  .yarn/cache/protocol-buffers-schema-npm-3.6.0-af2f375e69-8713b5770f.zip
  .yarn/cache/quick-lru-npm-6.1.1-6266dda1a4-a9c75bf1d2.zip
  .yarn/cache/quickselect-npm-2.0.0-620eb59fdc-ed2e784310.zip
  .yarn/cache/rbush-npm-3.0.1-9fc2a71778-b7def5ba76.zip
  .yarn/cache/resolve-protobuf-schema-npm-2.1.0-56c0d37a08-88fffab2a3.zip
  .yarn/cache/rw-npm-1.3.3-2197930a8d-c20d82421f.zip
  .yarn/cache/sort-asc-npm-0.1.0-4c54f663f3-c130223336.zip
  .yarn/cache/sort-desc-npm-0.1.1-0a4da19018-f2a2568f4e.zip
  .yarn/cache/sort-object-npm-0.3.2-94f9190a5e-701fac8b49.zip
  .yarn/cache/web-worker-npm-1.2.0-ef71df710e-1bb28348dd.zip
  .yarn/cache/xml-utils-npm-1.7.0-997c9a7089-3f933b87f0.zip
  components/map/view.vue
  layouts/map.vue
  package.json
  types/marker.ts
  utils/emotes.ts
  yarn.lock
Labels: enhancement

#38 feat: align sun with theme
  .yarn/install-state.gz
  components/easter-egg/button.vue
  components/easter-egg/confetti.vue
  components/easter-egg/orbit.vue
  components/easter-egg/sun.vue
  components/ui/ColorPicker.vue
  components/ui/NavMenu.vue
  layouts/map.vue
  pages/index.vue
  tailwind.config.ts
  utils/colors.ts
Labels: enhancement

#35 Updating Gallery Files
  content/gallery/121gwjolt.md
  content/gallery/lesheran.md
  content/gallery/phantasma-bosquet_de_lencelade-versailles.md
  content/gallery/phantasma-edinburgh_graveyard.md
  content/gallery/ryod-oasis_sant-alessio.md
Labels: enhancement

#42 feat: reduce icon size and zoom into clustered pins
  .yarn/cache/@types-ol-npm-7.0.0-0abcf3c338-b6fb074aa6.zip
  components/map/view.vue
  package.json
  yarn.lock
Labels: enhancement

#43 feat: add names to gallery images
  pages/gallery.vue
Labels: enhancement

#44 feat: add overlay names to images in map slideover
  components/map/view.vue
Labels: enhancement

#45 feat: add announcement on homepage
  components/announcement/Hero.vue
  content/announcement/birthday-2023.md
  pages/gallery.vue
  pages/index.vue
  tailwind.config.ts
Labels: enhancement

#27 Feat: new gallery images & updates
  .yarn/cache/@esbuild-win32-x64-npm-0.17.19-619fae7839-8.zip
  .yarn/cache/@esbuild-win32-x64-npm-0.18.11-26023a49d9-8.zip
  components/map/view.vue
  content/gallery/121gwjolt.md
  content/gallery/andreapower-cave.md
  content/gallery/andrewpower-monte_cengio.md
  content/gallery/andrewpower-passo_borcola.md
  content/gallery/cheezewolf-times_square.md
  content/gallery/cheezewolf.md
  content/gallery/dedicatus-berlin.md
  content/gallery/dedicatus-singapore.md
  content/gallery/dippezoid-amsterdam.md
  content/gallery/dippezoid-holland.md
  content/gallery/ebbii.md
  content/gallery/ercburger-animals.md
  content/gallery/ercburger-flags.md
  content/gallery/ercburger-pig.md
  content/gallery/ercburger.md
  content/gallery/eskimoish.md
  content/gallery/geolounge.md
  content/gallery/giackthedemon.md
  content/gallery/greenmst-singapore_expo.md
  content/gallery/greenmst.md
  content/gallery/ikanexus.md
  content/gallery/koalafrank.md
  content/gallery/lesheran.md
  content/gallery/mrgrimmlore.md
  content/gallery/no-coordinates.md
  content/gallery/phantasma-bosquet_de_lencelade-versailles.md
  content/gallery/phantasma-edinburgh_graveyard.md
  content/gallery/phantasma.md
  content/gallery/ryod-oasis_sant-alessio.md
  content/gallery/s-guy.md
  content/gallery/slowpoke.md
  content/gallery/spyrotk.md
  content/gallery/syrionino.md
  content/gallery/test.md
  content/gallery/thunderwing-ds.md
  content/gallery/tougrel.md
  content/gallery/vihilsta.md
  content/gallery/wikipera.md
  content/gallery/yuni.md
  content/gallery/zoiyya.md
  static/images/credits/phantasma.webp
  utils/credits.ts
Labels: enhancement, leaveopen

#48 feat(home): make announcement text look better in light mode
  components/announcement/Hero.vue
Labels: bug

#51 feat: add seo og-image and url
  app.vue
Labels: enhancement

#53 feat(map): add reset zoom button and prevent map rotation
  components/announcement/Hero.vue
  components/map/view.vue
  pages/gallery.vue
  tailwind.config.ts
Labels: enhancement

#56 feat: add more tougrel images
  content/gallery/phantasma.yaml
  content/gallery/tougrel_prosotsani.yaml
Labels: enhancement
