Repository Tougrel/Pestoverse, pull requests merged in 2024-01, with the labels that each got.

#88 feat: add scripts
  package.json
  scripts/fix-names.sh
  scripts/get-counts.sh
  scripts/update_image_sizes.mjs
  wrangler.toml
Labels: enhancement

#90 refactor: categories are visible by default
  package.json
  pages/awards.vue
  scripts/fix-names.sh
  scripts/get-counts.sh
  scripts/update_image_sizes.mjs
  wrangler.toml
Labels: enhancement

#92 Fix/awards
  pages/awards.vue
Labels: bug

#93 chore(docs): add database migration instructions to readme
  README.md
Labels: documentation

#94 feat: votes UI - we are fucking crazy
  app.config.ts
  components/awards/submissions.vue
  components/awards/votes.vue
  pages/awards.vue
  utils/emotes.ts
Labels: enhancement

#95 feat: cache emote images per submission + fix vote submit
  components/awards/votes.vue
  pages/awards.vue
Labels: enhancement

#96 feat: move state + secondary retrieval into functions to clean up a little
  components/awards/submissions.vue
  pages/awards.vue
Labels: enhancement

#97 fix/votes UI
  components/awards/votes.vue
  pages/awards.vue
Labels: bug

#98 feat: switch to votes after 00:00 on 12th January
  pages/awards.vue
Labels: enhancement

#100 feat: change cache for winners to 15 minutes
  server/api/votes/winners.get.ts
Labels: bug

#104 feat: close voting on 20th @ midnight
  pages/awards.vue
  server/api/votes/submit.post.ts
Labels: enhancement

#111 feat: add winners and stream reveal pages
  .yarn/cache/@babel-parser-npm-7.23.6-2fad283d6e-140801c437.zip
  .yarn/cache/@vue-compiler-core-npm-3.4.15-4f131dda24-1610f715b8.zip
  .yarn/cache/@vue-compiler-dom-npm-3.4.15-8299b45d96-373968c2c6.zip
  .yarn/cache/@vue-compiler-sfc-npm-3.4.15-3d3ce9fc16-4a707346c3.zip
  .yarn/cache/@vue-compiler-ssr-npm-3.4.15-05dd3d13a5-45a12ae2dd.zip
  .yarn/cache/@vue-reactivity-npm-3.4.15-fde29aa046-e1f8ef7ec3.zip
  .yarn/cache/@vue-runtime-core-npm-3.4.15-b9057fef14-6ab6721410.zip
  .yarn/cache/@vue-runtime-dom-npm-3.4.15-7dfc9b71f4-4f2e79d956.zip
  .yarn/cache/@vue-server-renderer-npm-3.4.15-fd81b21d4f-de93ccffe7.zip
  .yarn/cache/@vue-shared-npm-3.4.15-638dcb7e89-237db3a880.zip
  .yarn/cache/csstype-npm-3.1.3-e9a1c85013-8db785cc92.zip
  .yarn/cache/postcss-npm-8.4.33-6ba8157009-6f98b2af4b.zip
  .yarn/cache/vue-flip-npm-3.0.2-59f5e56813-78b70c1a7e.zip
  .yarn/cache/vue-npm-3.4.15-11fe9fcc84-6e9ff02c9b.zip
  assets/css/index.css
  components/awards/winners.vue
  package.json
  pages/awards/index.vue
  pages/awards/stream.vue
  plugins/vue-flip.ts
  server/api/submissions/categories.get.ts
  server/api/submissions/names.get.ts
  server/api/votes/options.get.ts
  server/api/votes/release.post.ts
  server/api/votes/released.get.ts
  server/api/votes/winners.get.ts
  server/utils/cache.ts
  utils/index.ts
  yarn.lock
Labels: enhancement

#112 Development
  .yarn/cache/@babel-parser-npm-7.23.6-2fad283d6e-140801c437.zip
  .yarn/cache/@vue-compiler-core-npm-3.4.15-4f131dda24-1610f715b8.zip
  .yarn/cache/@vue-compiler-dom-npm-3.4.15-8299b45d96-373968c2c6.zip
  .yarn/cache/@vue-compiler-sfc-npm-3.4.15-3d3ce9fc16-4a707346c3.zip
  .yarn/cache/@vue-compiler-ssr-npm-3.4.15-05dd3d13a5-45a12ae2dd.zip
  .yarn/cache/@vue-reactivity-npm-3.4.15-fde29aa046-e1f8ef7ec3.zip
  .yarn/cache/@vue-runtime-core-npm-3.4.15-b9057fef14-6ab6721410.zip
  .yarn/cache/@vue-runtime-dom-npm-3.4.15-7dfc9b71f4-4f2e79d956.zip
  .yarn/cache/@vue-server-renderer-npm-3.4.15-fd81b21d4f-de93ccffe7.zip
  .yarn/cache/@vue-shared-npm-3.4.15-638dcb7e89-237db3a880.zip
  .yarn/cache/csstype-npm-3.1.3-e9a1c85013-8db785cc92.zip
  .yarn/cache/postcss-npm-8.4.33-6ba8157009-6f98b2af4b.zip
  .yarn/cache/vue-flip-npm-3.0.2-59f5e56813-78b70c1a7e.zip
  .yarn/cache/vue-npm-3.4.15-11fe9fcc84-6e9ff02c9b.zip
  assets/css/index.css
  components/awards/winners.vue
  package.json
  pages/awards/index.vue
  pages/awards/stream.vue
  plugins/vue-flip.ts
  server/api/submissions/categories.get.ts
  server/api/submissions/names.get.ts
  server/api/votes/options.get.ts
  server/api/votes/release.post.ts
  server/api/votes/released.get.ts
  server/api/votes/winners.get.ts
  server/utils/cache.ts
  utils/index.ts
  yarn.lock
Labels: enhancement

#114 Feat/new UI
  components/announcement/Hero.vue
  components/awards/winners.vue
  components/easter-egg/button.vue
  components/easter-egg/sun.vue
  components/easter-egg/v2/button.vue
  components/kudo/card.vue
  components/kudo/sidebar.vue
  components/ui/Auth.vue
  components/ui/Authentication.vue
  components/ui/ColorPicker.vue
  components/ui/Footer.vue
  components/ui/NavMenu.vue
  components/ui/Navigation.vue
  layouts/default.vue
  layouts/map.vue
  layouts/new.vue
  middleware/devs_only.ts
  package.json
  pages/awards/index.vue
  pages/awards/stream.vue
  pages/credits.vue
  pages/gallery.vue
  pages/index.vue
  pages/map.vue
  pages/v2/credits.vue
  pages/v2/gallery.vue
  pages/v2/index.vue
  plugins/vue-flip.ts
  server/api/votes/released.get.ts
  server/api/votes/submit.post.ts
  server/utils/cache.ts
  utils/credits.ts
  utils/index.ts
Labels: enhancement

#115 Development
  components/announcement/Hero.vue
  components/awards/winners.vue
  components/easter-egg/button.vue
  components/easter-egg/sun.vue
  components/easter-egg/v2/button.vue
  components/kudo/card.vue
  components/kudo/sidebar.vue
  components/ui/Auth.vue
  components/ui/Authentication.vue
  components/ui/ColorPicker.vue
  components/ui/Footer.vue
  components/ui/NavMenu.vue
  components/ui/Navigation.vue
  layouts/default.vue
  layouts/map.vue
  layouts/new.vue
  middleware/devs_only.ts
  package.json
  pages/awards/index.vue
  pages/awards/stream.vue
  pages/credits.vue
  pages/gallery.vue
  pages/index.vue
  pages/map.vue
  pages/v2/credits.vue
  pages/v2/gallery.vue
  pages/v2/index.vue
  plugins/vue-flip.ts
  server/api/votes/released.get.ts
  server/api/votes/submit.post.ts
  server/utils/cache.ts
  utils/credits.ts
  utils/index.ts
Labels: enhancement
